---
layout: post
title: Different Length List to Dataframe in R
subtitle: 对齐颗粒度
date: "`r Sys.Date()`"
author: Chevy
header-img: img/055.png
catalog: true
tags:
  - 技术学习笔记
style: plain 
knit: (function(input, encoding) {
  rmarkdown::render(input, output_dir = "../_posts/")})
output: 
  md_document:
    variant: markdown_github
    preserve_yaml: true
  # prettydoc::html_pretty:
  # theme: cayman
  # toc: yes
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = "../../ChevyXu.github.io/", base.url = "/")
knitr::opts_chunk$set(fig.path = paste0("img/", Sys.Date(), "/"))
# knitr::opts_chunk$set(echo = TRUE)
```

# Set a demo list
```{r}
# Your input list
gene_list <- list(
  GeneListA = c("A", "B", "C", "D", "E", "F"),
  GeneListB = c("A", "F", "H"),
  GeneListC = c("A", "C", "D", "H"),
  GeneListD = NA
)

print(gene_list)
```


# 2. Turn it into a dataframe
```{r set PAT, eval = F}
# Find the maximum length of the list elements
max_length <- max(sapply(gene_list, length))

# Create a data frame with columns named after list elements
gene_df <- as.data.frame(lapply(gene_list, function(x) {
  length(x) <- max_length # Extend each element to max length by padding with NAs
  return(x)
}))

# View the data frame
print(gene_df)
```

> We need to note that GeneListD could not be NULL

## Show you the difference
```{r}
# Your input list
gene_list <- list(
  GeneListA = c("A", "B", "C", "D", "E", "F"),
  GeneListB = c("A", "F", "H"),
  GeneListC = c("A", "C", "D", "H"),
  GeneListD = c()
)

print(gene_list)

# Replace NULL with empty character vectors
gene_list <- lapply(gene_list, function(x) if (is.null(x)) character(0) else x)

cat("===================================================================\n")

print(gene_list)
```
